<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.02" os="Windows 7" host="INPUHJLP06355"><DocLocation><![CDATA[C:\Git_Repo\UFT_Octane_Test\EasyApp]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[EasyApp]]></DName>
<Res><![CDATA[EasyApp]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="10" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:48]]></Time>
<TimeTick>1527777168</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:48]]></Time>
<TimeTick>1527777168</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:49]]></Time>
<TimeTick>1527777169</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:51]]></Time>
<TimeTick>1527777171</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:52]]></Time>
<TimeTick>1527777172</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:53]]></Time>
<TimeTick>1527777173</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:55]]></Time>
<TimeTick>1527777175</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="51" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:56]]></Time>
<TimeTick>1527777176</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:57]]></Time>
<TimeTick>1527777177</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:02:59]]></Time>
<TimeTick>1527777179</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:00]]></Time>
<TimeTick>1527777180</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="83" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:01]]></Time>
<TimeTick>1527777181</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="91" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:03]]></Time>
<TimeTick>1527777183</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:04]]></Time>
<TimeTick>1527777184</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="107" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:05]]></Time>
<TimeTick>1527777185</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:22]]></Time>
<TimeTick>1527777202</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ txtLanId ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:22]]></Time>
<TimeTick>1527777202</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtLanId ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ txtLanId ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:22]]></Time>
<TimeTick>1527777202</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="122" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtLanId ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ txtLanId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SB0068667"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:23]]></Time>
<TimeTick>1527777203</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="125" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtLanId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Username Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:23]]></Time>
<TimeTick>1527777203</TimeTick>
<NodeArgs eType="User" icon="15" nRep="126" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Username Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:23]]></Time>
<TimeTick>1527777203</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="128" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ txtPassword ].SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5b069acd9a1d41aa2bf78fe2496f0d09e962cefe29e9025b9082acb46e1ea1a1"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:23]]></Time>
<TimeTick>1527777203</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ txtPassword ].SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Password Set]]></Obj>
<Details ><![CDATA[Successfully Set]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:23]]></Time>
<TimeTick>1527777203</TimeTick>
<NodeArgs eType="User" icon="15" nRep="132" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Login ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:24]]></Time>
<TimeTick>1527777204</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="134" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Login ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:24]]></Time>
<TimeTick>1527777204</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="137" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Login Button Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:24]]></Time>
<TimeTick>1527777204</TimeTick>
<NodeArgs eType="User" icon="15" nRep="138" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login Button Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ lnkLogout1 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:31]]></Time>
<TimeTick>1527777211</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="140" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ lnkLogout1 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ lnkLogout1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:32]]></Time>
<TimeTick>1527777212</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="143" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ lnkLogout1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Logout Button Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:32]]></Time>
<TimeTick>1527777212</TimeTick>
<NodeArgs eType="User" icon="15" nRep="144" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Logout Button Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ OK ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:35]]></Time>
<TimeTick>1527777215</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="145" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ OK ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:35]]></Time>
<TimeTick>1527777215</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="147" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[OK Button Click]]></Obj>
<Details ><![CDATA[Successfully Clicked]]></Details>
<Time><![CDATA[31/05/2018 - 20:03:35]]></Time>
<TimeTick>1527777215</TimeTick>
<NodeArgs eType="User" icon="15" nRep="148" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK Button Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/05/2018 - 20:02:45" eTime="31/05/2018 - 20:03:36" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="12" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="11" nRep="6" status="Passed" >
<Disp><![CDATA[EasyApp Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="31/05/2018 - 20:02:38" eTime="31/05/2018 - 20:03:36" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="9" nRep="3" status="Passed" >
<Disp><![CDATA[Test EasyApp Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>